// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oridlkljqrmgflewkhru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yaWRsa2xqcXJtZ2ZsZXdraHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNDUzODgsImV4cCI6MjA3MTkyMTM4OH0.LD5kKqLLcTw0wVb-UDo-39ZvM7oVa-LpIqN4XljZDtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});